Uniswap/web3-react

- README.md
Uniswap is a great starter project for people who want to build their first dapp. Let's add it here so people know web3-react is used there.
> Add Uniswap in README

- README.md
Thanks for this amazing framework! <3
> Update with link to NFT scribe project.

- packages/authereum-connector/package.json
- packages/authereum-connector/src/index.ts
Add support for various supported authereum networks + allow passing of config object
> Add mainnet + rinkeby chains for Authereum

- packages/walletlink-connector/package.json
- packages/walletlink-connector/src/index.ts
- packages/walletlink-connector/yarn.lock
This PR upgrades WalletLink to [2.0](https://github.com/walletlink/walletlink/blob/2.0.2/README.md) from 1.x
> Upgrade WalletLink to 2.0

- README.md
I actually thought I added it many months ago, but I see its not there, so here you go :)
> Add wildcards.world as a project using this library

- example/package.json
- example/pages/index.tsx
- example/yarn.lock
- packages/abstract-connector/README.md
- packages/authereum-connector/README.md
- packages/core/README.md
- packages/fortmatic-connector/README.md
- packages/frame-connector/README.md
- packages/injected-connector/README.md
- packages/ledger-connector/README.md
- packages/network-connector/README.md
- packages/portis-connector/README.md
- packages/squarelink-connector/README.md
- packages/torus-connector/README.md
- packages/trezor-connector/README.md
- packages/types/README.md
- packages/walletconnect-connector/README.md
- packages/walletconnect-connector/package.json
- packages/walletconnect-connector/src/index.ts
- packages/walletconnect-connector/yarn.lock
- packages/walletlink-connector/README.md
- yarn.lock
This updates `@walletconnect/web3-provider` to `1.0.8` to enable the awesome new mobile deep-linking feature.
> Update wallet connect to 1.0.8

- example/package.json
it's the little things in life 🌈
> Missing package breaking example project

- README.md
https://github.com/ethereum/eth2.0-deposit/blob/dev/package.json
> Add Eth2 Launchpad to projects

- example/connectors.ts
- example/yarn.lock
- packages/walletlink-connector/package.json
- packages/walletlink-connector/src/index.ts
Updates the WalletLink connector to fix issue from unbound `this`.
> Fix unbound this in WalletLinkConnector

- packages/walletconnect-connector/package.json
- packages/walletconnect-connector/yarn.lock
fixes server load issues 
from walletconnect: https://twitter.com/WalletConnect/status/1419999849068564505
> bump walletconnect to 1.5.0

- packages/example/connectors/index.ts
- packages/example/connectors/walletLink.ts
- packages/example/package.json
- packages/walletlink/package.json
- packages/walletlink/src/index.ts
- packages/walletlink/tsconfig.json
This PR adds a `WalletLink` connector to the alpha version of w3r. Connector code is very similar to MetaMask one. 
Preview:
> add WalletLink connector

- packages/walletlink-connector/package.json
- packages/walletlink-connector/yarn.lock
walletlink 2.2.6 includes a fix for this issue https://github.com/walletlink/walletlink/issues/149
> fix: Update walletlink to 2.2.6 to fix bug

- packages/network-connector/src/index.ts
> Update network-connector to specify POST Content-Type header

- packages/metamask/src/index.ts
> try out disconnect on lock

- packages/walletconnect/src/index.ts
closes #366 
closes #370 
these are both ultimately things that should be handled by walletconnect, but these small hacks work for now
> add some error handling

- packages/walletlink-connector/package.json
- packages/walletlink-connector/yarn.lock
Fixes https://github.com/walletlink/coinbase-wallet-sdk/issues/303
> fix: update walletlink to 2.4.7

- packages/core/package.json
- packages/core/yarn.lock
- packages/eip1193/package.json
- packages/eip1193/yarn.lock
- packages/example-next/package.json
- packages/example-next/yarn.lock
- packages/magic/package.json
- packages/magic/yarn.lock
- packages/network/package.json
- packages/network/src/index.spec.ts
- packages/network/src/index.ts
- packages/network/yarn.lock
- packages/store/package.json
- packages/store/yarn.lock
- packages/url/package.json
- packages/url/src/index.spec.ts
- packages/url/src/index.ts
- packages/url/yarn.lock
> fix: Compatible with @ethersproject/experimental 5.6.0

- package.json
- packages/coinbase-wallet/src/index.ts
- yarn.lock
Update coinbase-wallet connector to handle disconnect event
> Update coinbase-wallet connector to handle disconnect event

- packages/core/package.json
- packages/core/src/hooks.ts
- packages/store/package.json
- packages/types/package.json
- yarn.lock
Upgrades to a stable release of zustand. Fixes #743.
> build: upgrade to zustand@^4

- packages/network/src/index.ts
> fix: typo in code comment

- packages/walletconnect-v2/package.json
- yarn.lock
> fix: patch dependencies to fix wcv2 issues

- example/package.json
- packages/walletconnect-v2/package.json
- yarn.lock
> fix: update walletconnect v2 packages

- packages/walletconnect-v2/package.json
- yarn.lock
Adds more improvements / bug fixes based on the issues we sent to the WC team.
> chore: upgrade @walletconnect/ethereum-provider

- packages/walletconnect-v2/package.json
- yarn.lock
Should see some further improvements around errors that were getting thrown.
> chore: upgrade @walletconnect/modal, @walletconnect/ethereum-provider
