Uniswap/web3-react

- packages/authereum-connector/src/index.ts
Adds `close()` to the Authereum connector to allow users to disconnect from Authereum.
> Add close() to authereum connector

- packages/core/src/normalizers.ts
In the current version (0.2.13) of MetaMask Mobile, `ethereum.chainId` starts with “Ox” rather than “0x”.
The fix should be in the next version, but we might want to keep this for a bit until MetaMask Mobile users are up to date.
Reference: https://github.com/MetaMask/metamask-mobile/pull/1275
> MetaMask Mobile compatibility fix

- packages/portis-connector/src/index.ts
reference: https://docs.portis.io/#/configuration?id=network
> added other supported networks to the portis connector

- packages/network-connector/src/index.ts
Inside ethers.js web3-provider the request from buildEip1193Fetcher function looks like this:
`return provider.request({ method, params });`
In web3-react network-conenctor's `MiniRpcProvider` class, the `request` method overwrites `method` argument in a way that `params` will always end up undefined unless the `method` argument is a string and `params` is passed separately.
This pull request fixes this behaviour.
> Fix compatibility with ethers.js buildEip1193Fetcher

- README.md
We'd like to add our project to the list of projects using web3-react. You can read our manifesto [here](https://www.outpost-protocol.com/post/0CDUvbFIFhMgQ2Bc44CsVZRC0atSCs8X1wo16fHORiE)
> Added Outpost to projects using web3-react

- packages/authereum-connector/src/index.ts
- packages/fortmatic-connector/src/index.ts
- packages/portis-connector/src/index.ts
- packages/squarelink-connector/src/index.ts
- packages/torus-connector/src/index.ts
- packages/trezor-connector/src/index.ts
- packages/walletconnect-connector/src/index.ts
- packages/walletlink-connector/src/index.ts
This solves an issue where in some cases, the imported module returns the default export directly, rather than being on the `.default` property.
In CJS, the `import()` calls get transformed into `Promise.resolve(require("dependency"))` calls. Bundlers seem to stick to
CJS in this case, and pick the `main` field of the dependency, which is usually CJS with a `.default` prop.
In ESM, the `import()` calls don’t get transformed. In this case, bundlers seem to behave in different ways, by following one of the `main`, `module` and `browser` fields. In these two last cases, the default export is available directly and not on the `.default` property.
By checking if `.default` is defined and using the imported value otherwise, we make these imports compatible with these different
scenarios.
> Dynamic imports: only use .default when present

- docs/connectors/README.md
Hi! Just a quick fix to a link in the README.md of docs/connectors.
Thanks for your great work!
> Fix link to top-level README

- packages/walletconnect-connector/package.json
- packages/walletconnect-connector/src/declarations.ts
- packages/walletconnect-connector/src/index.ts
This PR adds support for any network to wallet connect connector. Additionally, exposes all the available config from wallet connect, so you can have more flexibility.
Closes #152 
Wallet Connect can be used with any network, as shown in https://docs.walletconnect.org/quick-start/dapps/web3-provider#setup
However, the current implementation of the connector was only allowing its use in Mainnet: https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/walletconnect-connector/src/index.ts#L31
Now you can construct the connector using `IWalletConnectProviderOptions` which has all wallet connect parameters.
```ts
// We can specify any other network
const provider = new WalletConnectConnector({
rpc: {
1: "https://mainnet.mycustomnode.com",
3: "https://ropsten.mycustomnode.com",
100: …
```
> Allow to use wallet connect with any network

- packages/walletlink-connector/package.json
- packages/walletlink-connector/src/index.ts
This PR updates WalletLink to the latest version (2.1.0) and adds event listeners for the `chainChanged` and `accountsChanged` events.
> Update WalletLink to 2.1.0

- packages/walletlink-connector/src/index.ts
- Add support for falling back on injected connector if user is attempting to connect via dapp browser on Coinbase Wallet
- Fix chainId method in walletlink-connector
- Don't use deprecated method for `eth_requestAccounts` request
> Fix misc walletlink connector issues

- packages/portis-connector/src/index.ts
Hardhat uses 31337 for their local dev chain. See docs: https://hardhat.org/config/#hardhat-network
This is helpful when testing DApps in development.
> Added 1337 & 31337 to Supported Chain IDs of Portis Connector

- packages/walletlink-connector/package.json
- packages/walletlink-connector/yarn.lock
Updates v6 with walletlink 2.4.6 which has support for addEthereumChain for unknown networks.
> fix: use walletlink 2.4.6 which has support for addEthereumChain

- packages/walletlink-connector/package.json
- packages/walletlink-connector/yarn.lock
Updates v6 with walletlink 2.5.0 which has support for [watchAsset](https://github.com/coinbase/coinbase-wallet-sdk/pull/336) for custom tokens.
> fix: use walletlink 2.5.0 which has support for wallet_watchAsset

- packages/walletconnect-connector/src/index.ts
hello,
this PR changes some code that was introduced recently in https://github.com/NoahZinsmeister/web3-react/pull/360/files
I'm not sure how the code was tested but for me, it just does not work - eg. calling `this.walletConnectProvider.wc.connected` gives me `Cannot read property 'connected' of undefined`
Indeed, if you check the source [code](https://github.com/WalletConnect/walletconnect-monorepo/blob/1.7.1/packages/providers/ethereum-provider/src/index.ts) of `@walletconnect/ethereum-provider` at the respective version, there is no `wc` property so the call is bound to fail.
I have replaced the occurrences of `this.walletConnectProvider.wc` by `this.walletConnectProvider.connector` which seems to be the appropriate property. There is a `wc` property that can be accessed under …
> fix: do not access undefined property in wc connector

- package.json
- packages/walletlink/package.json
- packages/walletlink/src/index.spec.ts
- packages/walletlink/src/index.ts
- yarn.lock
`walletlink` became deprecated and has been moved to [@coinbase/wallet-sdk](http://npmjs.com/@coinbase/wallet-sdk). This PR replaces all the imports.
> fix: upgrade walletlink to `@coinbase/wallet-sdk`

- packages/walletlink-connector/package.json
- packages/walletlink-connector/src/index.ts
- packages/walletlink-connector/yarn.lock
[walletlink](https://www.npmjs.com/package/walletlink) project has been renamed to [@coinbase/wallet-sdk](http://npmjs.com/@coinbase/wallet-sdk). This PR replaces all the imports keeping its same API.
> update walletlink-connector to use @coinbase/wallet-sdk over walletlink

- packages/core/src/hooks.spec.ts
- packages/core/src/hooks.ts
- packages/example-next/components/Accounts.tsx
- Forces a re-render after lazy-loading @ethersproject/providers. This was not done before because the re-render is only forced if state _changes_.
- Cancels state updates if the hook's component is unmounted (with a `stale` guard).
- Cleans up hooks tests to use idiomatic @testing-library/react (eg `result.current`, which auto-updates when the component is re-rendered due to state changes).
> Fix useProvider

- package.json
- packages/walletconnect/package.json
- yarn.lock
https://github.com/Uniswap/web3-react/pull/702#issuecomment-1310195922 set the peerDep to 1.7.9, but after testing I noticed this was not a valid version. In the future we should require the examples to get updated as well for verification.
> fix: change @walletconnect/ethereum-provider to valid version

- packages/metamask/src/index.ts
The error 1013 shouldn't lead to the wallet disconnection, because it's just an attempting to reestablish the connection.
It blocks https://github.com/cowprotocol/cowswap/pull/924
> Ignore the MetaMask error with code 1013

- packages/coinbase-wallet/src/index.spec.ts
- packages/coinbase-wallet/src/index.ts
- packages/eip1193/src/index.spec.ts
- packages/eip1193/src/index.ts
- packages/eip1193/src/mock.ts
- packages/metamask/src/index.spec.ts
- packages/metamask/src/index.ts
- packages/walletconnect/src/index.spec.ts
- packages/walletconnect/src/index.ts
Serially requests `accounts` and then `chainId`, so that if a user changes chains whilst connecting, the new chain (after connection / `accounts`) will be used. Practically, this prevents web3-react from using incorrect initial state when connecting to certain wallets, in certain cases where the user selects a non-active chain. This is resolved by waiting for `accounts` to settle before requesting `chainId`.
---
For `chainId` and `accounts`, the values were fetched using a `Promise.all`. In some wallets, `chainId` resolves immediately, and then the user is prompted to change chains. In these cases, `chainId` will be outdated by the time `accounts` resolves:
1. `eth_chainId` resolves to "stale" chain
2. user is prompted to connect with a chain selector
3. user selects a different "active" …
> fix: use up-to-date chainId/accounts when querying EIP1193-derived wallets

- packages/core/package.json
- packages/store/package.json
- packages/types/package.json
- yarn.lock
Pinning down Zustand to 4.3.3 as 4.3.4 is causing a regression as can be seen by checking the CI build status for each of the commits in this PR.
Reported here: https://github.com/pmndrs/zustand/issues/1662
> fix: temporarily pin zustand version to 4.3.3

- example/components/Card.tsx
- example/components/ConnectWithSelect.tsx
- example/components/ProviderExample.tsx
- example/components/connectorCards/WalletConnectV2Card.tsx
- example/connectors/walletConnect.ts
- example/connectors/walletConnectV2.ts
- example/next.config.js
- example/package.json
- example/pages/index.tsx
- example/utils.ts
- packages/types/src/index.ts
- packages/walletconnect-v2/package.json
- packages/walletconnect/README.md
- packages/walletconnect/package.json
- packages/walletconnect/src/index.spec.ts
- packages/walletconnect/src/index.ts
- packages/walletconnect/src/utils.spec.ts
- packages/walletconnect/src/utils.ts
- packages/walletconnect/tsconfig.json
- yarn.lock
Initially, we deprecated WalletConnect V1 and replaced it immediately with V2. We have made decision internally that we're going to ship both packages side by side till V1 is deprecated, instead of bumping major version and cutting legacy branch. This PR brings back V1. 
Changelog:
- dropping peer dependencies in favour of dependencies so both WC can run side by side
- added `@walletconnect/types` dependency that was missing before inside `walletconnect` (v1) package
- bumped version locally to latest published to `npm` (which is currently v2), next publish will bring downgrade `@web3-react/walletconnect` back to v1
PS. I did `git mv` to move `walletConnectCard.tsx` to `walletConnectV2Card.tsx` but unfortunately, that didn't help with the diff - it still reports that I did changes in …
> feat: bring back walletconnect v1

- packages/core/package.json
- packages/store/package.json
- packages/types/package.json
- yarn.lock
We have run into a bug in Zustand 4.3.4 that just got fixed https://github.com/pmndrs/zustand/commit/0c153cac18f3b9b6371b03d1ce537f8d10915dca and released under `4.3.5`.
> fix: unpin `zustand` now that upstream issue is resolved

- packages/walletconnect-v2/src/index.ts
Fixes INFRA-137
Fixed upstream via https://github.com/WalletConnect/walletconnect-monorepo/commit/1c739200e3a9185b9130f3069be8e6871f258887
We have updated WalletConnect in another PR recently to fix another issue and that was shipped in the meantime.
> fix: chain WalletConnect 2 `on` and `removeListener` methods 

- packages/walletconnect-v2/package.json
- yarn.lock
Recent change to `@walletconnect/ethereum-provider` led to moving `@web3modal/standalone` to peer dependencies. This was motivated by other dependencies that rely on Ethereum Provider and not necessarily display QR code after all. 
After discussing with WalletConnect team, the recommended solution is for end dependencies (such as Web3React or Wagmi Connector) to explicitly add `@web3modal/standalone` if relying on it to provide functionality. 
In our case, we do not support integrating modals in a different way, so it makes sense to continue relying on the behavior that was the default prior to `2.5.0` release.
> fix: add web3modal/standalone dependency

- packages/eip1193/package.json
- packages/eip1193/src/index.spec.ts
- packages/eip1193/src/mock.ts
- packages/walletconnect/src/index.spec.ts
- packages/walletconnect/src/index.ts
Aligns eip1193 with other providers that already use eventemitter3. Removes some unused imports in the test suite too.
> feat: replace node:events with eventemitter3

- packages/coinbase-wallet/src/index.spec.ts
- packages/core/src/index.tsx
- packages/core/src/mocks.ts
- packages/core/tsconfig.json
- packages/eip1193/src/index.spec.ts
- packages/eip1193/tsconfig.json
- packages/metamask/src/index.spec.ts
- packages/walletconnect-v2/src/index.spec.ts
- packages/walletconnect/src/index.spec.ts
- tsconfig.json
Updates some test suites, mostly WC2 by removing custom provider and re-using existing one. Also, makes it generic, so that it accepts both number and string, making implementation of wc test suite much smaller.
> feat: export and share MockEip1193 provider and use it throughout the test suite

- packages/eip1193/src/index.spec.ts
- packages/walletconnect-v2/src/index.spec.ts
This was result of my misunderstanding of the `Provider` type. We should not narrow it down because it's mostly used in abstract class `Provider` and not directly interacted with. Most of the time, you're calling `request` off WalletConnect/MetaMask/GnosisSafe providers, and they have their own types. This is an exception for Eip1193, but this is not what the original intention of this todo was.
> chore: remove todo from WC2 test suite

- packages/eip1193/src/index.spec.ts
As per discussion here: https://github.com/Uniswap/web3-react/pull/792#discussion_r1158521514
> chore: ensure Eip1193 test suite has mocks that implement all properties of `ProviderRpcError`

- packages/walletconnect-v2/package.json
- yarn.lock
This will reduce a sentry error we're seeing `No matching key`.
https://uniswap-labs.sentry.io/issues/4252488102/?end=2023-06-23T14%3A08%3A59&project=4504255148851200&query=release%3A9202f2e2e4e9360c02478543206eb034944ac647&referrer=issue-stream&sort=freq&start=2023-06-22T20%3A18%3A00&stream_index=0
> chore: upgrade @walletconnect/ethereum-provider

- packages/gnosis-safe/package.json
- yarn.lock
The Safe SDK version `7.10.0` contains a [bug](https://github.com/safe-global/safe-apps-sdk/pull/470) related to passing the SDK version for checking if a particular feature is compatible with the SDK/safe wallet interface. This renders the uniswap's interface permit2 flow unusable because signing a message in the Safe wallet is only available from a particular version, and the SDK currently passes an invalid version number.
This was fixed in `7.10.1`, and in version 8, Safe SDK migrated from `ethers` to `viem` under the hood and shaved off ~50% of the SDK package size.
This PR updates the SDK version of the connector to `8.0.0` and pumps the connector package version.
- An e2e swap of an erc20 token in the uniswap interface
> fix(@web3-react/gnosis-safe): bump safe sdk version to fix the signing issue

- .github/workflows/CI.yml
- .github/workflows/snyk_sca_scan.yml
- .snyk
- package.json
- yarn.lock
- Integrating Snyk test/monitor for web3-react
- Excluding workspace's unmet dependencies as lerna is used for the monorepo management and web3-react component included as a dependency to other projects e.g., CoinbaseWallet, etc. 
- uses Lerna for managing monorepo and Yarn workspaces
> build: Snyk test/monitor for web3-react + exclude workspace unmet deps

- .snyk
Snyk reported vulnerabilities recently that have no direct upgrade yet or were false-positive. We just updated the `lerna` to major version `^5.0.0`
---
```
snyk ignore --id='SNYK-JS-NWSAPI-2841516' --expirty='2024-01-01' --reason='no direct update or patch available suggested for jest / most probably vuln is not reachable'
snyk ignore --id='SNYK-JS-TOUGHCOOKIE-5672873' --expirty='2024-01-01' --reason='no patch or suggestion is available by jest'
snyk ignore --id='SNYK-JS-WORDWRAP-3149973' --expirty='2024-01-01' --reason='ReDoS is valid when there is a path between the source (user uncontrolled input) to a sink that is a regex parser but in this case is not applicable'
snyk ignore --id='snyk:lic:npm:rlp:MPL-2.0' --expirty='2024-01-01' --reason='introduced through Coinbase Wallet and …
```
> build: Snyk ignore policy for unreachable/false-positive reported vulnerabilities 

- packages/core/package.json
- packages/core/src/hooks.ts
- packages/store/package.json
- packages/types/package.json
- yarn.lock
Fixes https://github.com/Uniswap/web3-react/issues/871
Built successfully
Since 4.4.0, Zustand's dev deprecated the use of useStore() with an equality function.
> Fix zustand warning
